### ISSUE TITLE
Neat library! English simply()

### ISSUE THREAD

**Issue by TheDigitalOrchard** [Hikuroshi/terbilang-number-to-word#1]
Very neat library! Should come in handy.

Just some friendly feedback about English...

`11111`

Would be read as "eleven thousand ONE hundred eleven", not "eleven thousands A hundred eleven"

`24434`

Would be read as "twenty four thousand four hundred AND thirty four", not "twenty four thousand and four hundred thirty four"

The AND goes before the final number.

**Comment by Hikuroshi** [comment]
Hi @TheDigitalOrchard ,

Thank you for your feedback and for pointing out these details regarding the English number conversion!

Regarding the issue of reading numbers like "11111" as "eleven thousand ONE hundred eleven" instead of "eleven thousands A hundred eleven," please note that the `simply()` method is designed to simplify the representation of numbers. If you want the standard reading without simplifications, please do not use the `simply()` method. Additionally, the `simply()` method allows you to selectively simplify only the chosen words.

As for the reading of numbers like "24434" as "twenty four thousand four hundred AND thirty four" instead of "twenty four thousand and four hundred thirty four," my library currently does not support inserting "and" between words.

If you have any further suggestions or need more assistance, feel free to let me know!

Best regards,
Hikuroshi
